name: Client

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./client/node_modules
          key: modules-${{ hashFiles('./client/package-lock.json') }}
          
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Run unit tests
        run: npm run test:headless